
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dckdewhjdfkdbuefnaxw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRja2Rld2hqZGZrZGJ1ZWZuYXh3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM1OTE5MTEsImV4cCI6MjA1OTE2NzkxMX0.gX6R_Ps85Ok06wTd6N8gSNPE90cYDtJ60GXQamU_d8I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Create Supabase client with custom types for contact_messages table
export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);

// Add custom types for the contact_messages table
export type ContactMessage = {
  id: string;
  user_id: string | null;
  name: string;
  email: string;
  message: string;
  created_at: string;
  resolved: boolean;
};
